name: "Test Almanac"
on:
  pull_request:
    branches: [ main ]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-21.05
    - run: nix-build ./nix/release.nix
    - run: nix-shell --run "cabal new-test --test-show-details=streaming --test-option=--color"
